(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"kerkenbush_midterm_1_atlas_1", frames: [[468,133,1330,93],[0,0,466,775],[468,0,1059,131]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.CachedBmp_12 = function() {
	this.initialize(ss["kerkenbush_midterm_1_atlas_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_11 = function() {
	this.initialize(ss["kerkenbush_midterm_1_atlas_1"]);
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_10 = function() {
	this.initialize(ss["kerkenbush_midterm_1_atlas_1"]);
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_9 = function() {
	this.initialize(img.CachedBmp_9);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,3102,867);


(lib.CachedBmp_8 = function() {
	this.initialize(img.CachedBmp_8);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,3423,875);


(lib.CachedBmp_7 = function() {
	this.initialize(img.CachedBmp_7);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,2649,776);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.window = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#330000").ss(13,1,1).p("AQfQLIMqAAIAAMqIsqAAgAg2kmIQsAAIAAONIwsAAgA9I80IXcAAIAAUeI3cAAg");
	this.shape.setTransform(135.55,140.525);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFCC00").s().p("AQfc1IAAsqIMqAAIAAMqgAg2JnIAAuNIQsAAIAAONgA9IoWIAA0eIXcAAIAAUeg");
	this.shape_1.setTransform(135.55,140.525);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("ArtKPIAA0dIXbAAIAAUdg");
	this.shape_2.setTransform(24.05,21.55);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFCC00").s().p("ACWQuIAAsqIMqAAIAAMqgAu/ifIAAuOIQsAAIAAOOg");
	this.shape_3.setTransform(226.05,218.025);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape}]},19).to({state:[{t:this.shape_1},{t:this.shape}]},20).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape}]},20).to({state:[{t:this.shape_1},{t:this.shape}]},15).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-57.4,-50.4,386,381.9);


(lib.title = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.CachedBmp_12();
	this.instance.setTransform(-247.3,-28.45,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.title, new cjs.Rectangle(-247.3,-28.4,665,46.5), null);


(lib.plantpot = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#663300").ss(6,1,1).p("AidgTQAAAWAAAWQAAADAAACQAJgGAEgTQACgJAGgJQAEgJAFgHQAEASAGAQQAJgFALAAQAAAPAAAPQAHgWADgWQAJABgBANQAAAIACAHQAGAGAIgRQAEgGACgHQAAgDAAgCQAMAYgCAeQANgMAGgbQAEgNAHgMQADgFACgFQAGAYgBAZQASgZAQgdQAKABgBAOQgBAMAAAMQABAQAGAOQAIgFAHAAQADAFACAAQAIgTANgPQAHAHAJAFQAEACAEgCQADAAADgCQAKgEADAGQACACAFAAQAMAAANAA");
	this.shape.setTransform(-0.2,-15.45);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#CC3300").ss(2,1,1).p("AkXiLQhygoByg8QEhiIEiBlQBLAwhLBDAiai4QCuBMCvhMAiLjvQCmhVCoBVAkXiLQEhBFEihZAkXiLQBCC3gBDJQDnCSDpiSQgYjKBKjK");
	this.shape_1.setTransform(-4.9305,5.5215);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FF9900").s().p("AjWD1QABjJhCi3IACABQB9AdB+AAIAAAAIAAAAQCjAACjgyQhKDKAYDKQh0BJh1AAQhzAAh0hJgAgahtQh+AAh9gdIgCgBQhygoByg8QEhiIEiBlQBLAwhLBDQijAyijAAIAAAAIAAAAgAAUiSQBXAABYgmQhYAmhXAAQhXAAhXgmQBXAmBXAAgAAAipQAMgMAHgbQADgNAHgNIAGgKQAFAXAAAXIAAAEQATgaAQgdQAIABAAAMIAAACIAAARIAAAIQAAARAHANQAHgFAIAAQACAFADAAQAHgTANgQQAHAIAJAFIABABIADAAIABAAIABAAIABAAIABAAIAGgDIABAAIAEgBIABAAIABAAIAAAAIAAAAQAFAAACADQABACAFAAIAZAAIgZAAQgFAAgBgCQgCgDgFAAIAAAAIAAAAIgBAAIgBAAIgEABIgBAAIgGADIgBAAIgBAAIgBAAIgBAAIgDAAIgBgBQgJgFgHgIQgNAQgHATQgDAAgCgFQgIAAgHAFQgHgNAAgRIAAgIIAAgRIAAgCQAAgMgIgBQgQAdgTAaIAAgEQAAgXgFgXIgGAKQgHANgDANQgHAbgMAMIAAgIQAAgZgJgWIgBAFQgCAIgDAHIgBABQgFAKgEABIgBAAIAAAAIgDgCIAAAAQgCgGAAgGIAAgDIAAgCQAAgMgIgBQgDAXgHAWIAAgeQgLAAgJAFQgGgRgEgSIgKAQQgFAJgDALQgEATgIAFIAAgFIAAgtIAAAtIAAAFQAIgFAEgTQADgLAFgJIAKgQQAEASAGARQAJgFALAAIAAAeQAHgWADgXQAIABAAAMIAAACIAAADQAAAGACAGIAAAAIADACIAAAAIABAAQAEgBAFgKIABgBQADgHACgIIABgFQAJAWAAAZIAAAIIAAAAgADDjvQiohVimBVQBUgqBSAAQBUAABUAqg");
	this.shape_2.setTransform(-4.9305,5.5215);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.plantpot, new cjs.Rectangle(-39.6,-27.3,69.4,65.6), null);


(lib.Mathilda = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#663300").ss(2,1,1).p("AgTiJQAUAAAWgBQAHgBAIgBQAAAAABAAQARgEASgKQAEgCAEgCQAMgFAOgDAA/hRQAtgBAjgYQAFgDAFgCQALgGAKgHQALgHAKgIQACgCAEAAAA6gVQAPACANgCQAogDAbgbQAUgVAYgOQAFgCAGgDAAICiQAAgYAAgZQABgUABgUQAAgCABgDQACgHABgIQABgFABgFQAAgDAAgCQACgYgGgUQgBAAAAgBQgEgMgDgMIAAAAQgDgIgBgIQgDgOgGgHQgCgDgCgFQgBgBAAgCQAAgBAAgBQgCgXACgWQAAgIgFgDAgeiIQgDABgDABQgDAAgCABQgZACgaABQgIAAgHgBQgPgBgJgJQADgIAQACQAKABAKACQAFAAAFABQAOABAIAEQAEACAFAAQAKAAALAAQAFAAAGgBQgDgBgEABQgCAAgCABgABOAmQAEAAAEAAQAmAAAngCQACAAADgDQAVgQASgTQAIgJAJgJQAEgDAFgDAAICiQADgBADgBQAEgCAFAAQAoACAmgFQAIgBAJgBQAygIAygGQAEgBAFAAQACgBADAAQAZgGAZgFQAKgCADgFQADgDACgEQADgEAAgFQAAgagHgYQgBgCgBgDQAAAAAAAAQgIgRgNgSQgNgUgKgZQgHgSgFgVQgEgOgEgNQgBgBAAgCQgFgNgHgMQgEgIgDgJQgBAAAAgBQgEgKgCgMAB2BxQAgABAfgJQAFgCAGgCQAagKAZgHQAcgIAMgXAkRBcQgCADgCADQgFAIgFAMQgGAOgJAGQAHAJASgBQAFAAAFACQASAFASAEQAGABAGABQABABABAAQADABADAAQAWAFAWAAQBJACBJgCQAHAAAIgBQAIgBAGgCAjigbQgFAYgKAVQgGANgEAMQAcgBAbAEQARACARgBQAXgBAOAFQAEACAEABQAPADAPABQANAAANAAAkGArQAGAAAFAAQgBACgBADQgHAVgNAXQAfANAfAGQAJACAKAAQBCAABBAAAjbhRQAXADAUAEQACAAAAABQACAAABAAQAcAGAfABQAKAAAKAAQAQAAAPAAAjbhRQgCATgCAQQgBAKgCAJQAAAAAAAAQAXACASAEQARADARAGQAVAHAXADQAaADAUgMAjbhTQAAABAAAB");
	this.shape.setTransform(3.8,138.25);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#000000").ss(2,1,1).p("ABLlAQgFgEgGAEIAAAAQgEACgEABQgCAAgCAAQgDACgEAAQgDAAgCAAQgEAAgDABQgEAAgEABQAEAAAEAAQAEgBADAAQADAAACgBQAEAAAEgBQABAAACgBQAEADAEgDQAHAAAGAAAAQk3QAAABABAAQAIADAIABQAGABAGAAIAAAAQAGAAAHgCIABAAQADAAADAAQAFgBAFgDQACgBAAgFQAAgBgCgCQAAAAAAAAABAk9QADgEAIABAgblRQADACADABQAMAGALADQAKADAKACQADABACABQADAAACAAQAEAAADABQADAAADAAQAEAAADAAQACAAACAAQAEAAAEAAAAJk6QADACAEABQgDABgCACQgEABgFAAQgFABgFgBQgKgCgDgIQgBgCgBgEQANgBAKAFQAFACAEADQAIABAIAAQgFABgEABABNBYQgKABgDgKQgCgEgCgEQgDgDgBgFQgBgDgDgCQgcgggVgYQgDgEgCgFQgQgagRgXQgBAAAAgBQgCgDgBgCAAqBYQgCgOgLgNQgJgLgJgMQgJgNgHgNQgMgTgJgUQgFgKgDgOQAAgCgBgDAhSFSQAigZAagUQAVgQAKgNQADgEADgEQAJgLADgMQAIgGAAAGQAAACABADQALAWAeAFQADAAADADAgYk8QACAAABgBQAOgDAGAEQADAEAHgC");
	this.shape_1.setTransform(-0.7,83.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#FFCC66").ss(6,1,1).p("AATiCIAAgBQgCgDgFgKQACgDAAgCQgBgRgGgNAATiCQACgCAGgCAArBVQAHgRAIgQQAAAAABgBQAGgYgCgbQgBgYgCgcIAAAAQgDgCgGgBQgJgJgGgJQgCgEgCgCQgFgEgDgFQAAAAAAAAQgDgEgBgFQgBAAAAAAQAAgCgBgBQgDgNAEgPQAAgBAAgBAAmBjQgGAOgFAQQAGgPAMgHQAEgCADgFQAFgHAGgIQALgMAAgSQAAgCABgDQACgMACgNQAAgCABgDQACgMABgMQACgWgIgNQgCAAgBAAQgFgCAAgGQgBAAAAAAQgKgKgHgMQAAgBgBgCQgBgBgBgBQgGgHgFgIQgDgFgCgEQAAgBAAAAIgBAAQgCgFgEgEQAAgBAAAAQADgNgJgIAhSgTQAFgRAOgIQADgDACgCQAOgVAPgUQAEgEADgEQABgCABgCQABgCABgDQADgHAAgKQAAgFABgFQACgKAAgKAgMC0QgQgcgMgSQgCgEgCgFQgGgUgFgUQgCgHAAgIQAAgPAAgP");
	this.shape_2.setTransform(1.394,61.55);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#336633").ss(2,1,1).p("AAymKQAWACARAFQADAAADABQAAAAAAAAQAMACAMACQADAAADABQAXAFAHAQQACADACADQATATARAMQAKAHAKAFQAAABAAAAQAMAGALAHQAEADABAFQAAACAAACQAAABAAAAQAAACAAABQABAIgBAJQgCAUgKAHQgEADgEAEQgGAGgFAGQgJAJgGAHQgDADgCAEQgFAJgDARQgCAKgEAJQgEANgGARQgEAKAAALQAAAFAAAFQgUgYgWgcQgDgDgBgFQgHgXgHgRQgHBgACBiQAAAjACAjQABAFABAFQAHAlARAYQACAEACAEQABADABADQAEAKAAAKQABALADAGQABACABABQgGABgEACQgEACgFAAQgMACgNACQgMABgLAEQgCABAAAFQAAADAAADQAPAEAMAHQADADAFABQADABADABQAMACAMAAAD5kcQAYgCASAOQADADAFABQAXAHARAMQALAIAPAKQAbATAWAOQAcASATAeQAIANAIAOQAHALAEAIQAFAJAFAKQAEAIADAHQAHATACAbQAAAFACAEQABADAAADQABAMAEAIQAFAJAEAJQAFAMAEANQAPAugEA3QgCAbADAcQAAAKgGAEQgCABgCAEQgJAPgNAQQgMAQgYAIQgKADgKADQgYAFgagBQgagBgYAEQgMADgNAAQgZAAgZACQgCAAgDABQgYAFgZAEQgBAAgBAAIAAAAQgCABgCAAQgZACgZgDQgCAAgDAAQgSgCgFgLQgCgEABgEQAAAAABAAIAAgBQAHgZAEgaQACgMgBgMQAAgHAAgHQgMgCgIABABek/QAcABAOALQADADAFABQADABACADQADAEAHABQAGACAJgCABfjpQAKAJANAHQAIAFAIADQAFACAGABQAHACAHAAABtkIQAVgEAPAGQAFADAFADQAKAIAOgBAEMAFQgvAFgfgeQgKgIgLgGQAbAHAYALQAPAHAPAJQAIAFAKAAgAExBGQABgXgFgSQgFgUgMgNQgRgSgOgaQgGgLgHgLQgEgIgHgLQAZAxAPAtQAAAAgBAAAFcANQABgBABgCQAOgTATgRQgJAMgKAKQgIAIgIAJgAExBGQAIgOAIgMQAHgJAIgJQADgDADgDQAAAAABgBQADgDACgDQgDAEgDADQgKAMgKANQgJAMgIANgAF/gaQAEgDAEgDQALgJAMgDQgSACgNAQgAEkCKQAFABAGgBQAugBAfgfQAPgQAOgGQADgCABgDQAGgOAKgFAEkCKQAFgGADgHQACgDAAgCQACgZABgZACjDJQABgSAIgMQACgEAFgDQAIgEAIgEQAXgJAagBQAUgBAUgCQAFgBADgEABKEIQAAASAAASQAAAIAKgBQAUgCAUgCQAGgBAFgBQAKgDAFgHQAAAAABAAQAEgEAEgCABFDhQADABACAAQAAATAAATQAPABAIAHQACADAFABQADABADABQAHACAHAAAkikmQgQABgNAJQgTAPgaAHQgDAAgDADQggAcgbAcQgGAGgGAMQgBADgDADQgRATgYATQgaAWgTAdQgJAQgEAZQgEATgBAUQgDAbACAcQAAAUACAUQABAHAAAIQAAATAGAQQAJAXAKANQACAEACAEQAEAHAFANQACADABADQAVAlApAaQAQAKASAHQADABACABQAAABABAAQAUAIAQALQADADAFABQADABADACQAXALAVADQANACAMACQADAAADABQAMACAMABQAQACAHgGQACgCAEgDQAEgCAEgEQAFgEAGgGQAHgGAIgIQAPgMAPgNQACgCgBgFQgBgDAAgCQAAgFABgGQAFgYAAgZQAAgcgLgOQgDgDgCgEQgKgXgMgTQgJgOgLgUQgDgFgCgFQgEgKgCgKQgCgIgBgIQAAAAAAAAQgCgJAAgKQAAgBAAgBQABgMAIgHIAAAAQgFAKgEAJQgGAQgEAQQAGgGAGgFQAjgeArgSQgGALgRAKQgEADgEADQgXARgVAUQgCACgDADAolgKQAcAfAZAVQAEADADAEQAZAkAnACQADAAACADAgymFQglgDghAGQgHACgHABQgQADgKAGQgJAFgPAGQgDABgCADQgOASgWAMQgBAAgBABQgBAAAAAAQgEACgDABQADAAAEAAQAAABABAAQABAAABAAQABAAABAAQAYADAYAEQADAAACAAQAcADAbAAAjijTQADAEADADQAQAYAOAQQAFAHAKADQAFACAEAEQAGAGAHAGQAJAKAJALQABABABABQAAABABAAQACADAFAAQASAAARgCQANgBAAgRQAAgDACgCQAAAAABgBQAAAAABgBQAAgJABgJQAAgDABgDAkTkNQAVADASgEQAGAAAGgCQAHgCAHgBQAZgFARANQADADAFABQADABADABQAHACAHAAAjijTQAsACAvACQADAAADABQAMACAMAAAjrlFQgTAGgRANQgCABgBACQgCADgBAGQAAAEAAAGQABAIABAHQABAKABAJQABADADACQAaAOARAUAjdgLQAEgDADgFQAPgcATgbQgZAfgQAggAhkEnQAAgKAAgKQAAgmgBglQgBgXAAgWQAAgIgBgHQgCgZgCgZQgBgQAGgHQACgCACgFQABgDACgDQAIgMgEgWQgBgKAFgHQACgDACgEQAMgngCguQgBgXABgWQAAgBAAgBQAJgMAEgQAi5ExQALANAOAIQADABACADQADACACADAiqFpQAAAAABgBQARgLAWgGQADgBADgBQAIgDAGgGQAAAAABgBQAIgIgFgSQgBgBgBgCQgBAAgBgBQgUgLgUgKQgFgDgHgFAjoFMQAVARAKAaQABAFABAEQACAGACAFQAOgLAIgTQAAgCADgCAjPE3QAVAeAQAU");
	this.shape_3.setTransform(0.639,89.55);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#FFCC66").ss(2,1,1).p("AAUp7QgCgBgBgCQgEgDgEgCQgJgDgJgBQgCAAgDgCQgNgHAAgXIAAAAQAAgDABgDQAAgBAAgCIAAAAQAAgBAAgCQAAgEABgEQABgNAAgNQAAgCAAgDAgIrsIAAAAQAAABAAABQAAAEAAADQAAARAAARQAAAGAAAGQAAACABABQAAAFAAAFIAAAAQABAIADAHQABADACACIAAAAQAOAPAGAKAiBqKQgDAKgEAKQgBADgBADQgCAEgCAFQgEAPAAAUQgBAEABAEQAAAUAFANQADAGACAFQACAEACADQAFALAHALQAFAJAFAKQAAAAAAABQAFAIAEAJQAFALAGAMQAGAMAKARQANAXAKAOQAFAGADAHQACADADACQAHAFAHAFQAMgTAGgVQACgHACgIQADgZAHgZQACgHACgHQAFgWAIgUQAAgBAAAAQABgBAAgBQAGgPAEgUQACgOABgRQABgLgBgKQAAgKgBgJQAAgFgEgDQgBgBgBgBQgDgDgEgCAgToIQAAgvgCgwQAAgFgDgEQgKgQgDgZQgBgHAAgHQgBgEAAgEQAAAAAAgBQAAgBAAgCQAAgFAAgEQAAgRAAgSAAHobQAIgRAIgPQACgEABgFQADgfgHgTQgBgDgBgCAgNnrQADgHADgHQACgOAIgMQACgDACgEADwK2QAAg+gCg/QAAgFgBgFQgJgvgJgvQgBgGAAgFQgBgngEgkQgDgRAAgSQAAgKgEgFQgDgFgDgFABLFYQACAbAHAYQAJAiAGAjQAQBcAABiQAAAXACAWQABADACACAgxFiQgDBSAKBOQABAIABAHQANA5AEA6QABASACARQABATADARQACAJACAKQABADACACAiQLtQA5AAA6AAQADAAACAAABuLPQAFAAAFAAQA8AAA8AAQADAAACAAQADAAACAAAhZrpQAAAFAAAEQgCAPgCAOQgBAFgBAFQAAAAAAABQAAAAAAABQgBADgBADQgCAMgEAIQgEAHgFAFQgCACgFAAAj5FYQAQAlARAsQAEAJAEAKQAJAUACAZQAAAIABAHQAHAwAJAvQABAIABAHQAGAnALAlQACAEABAFQAHATAHAa");
	this.shape_4.setTransform(6.55,120.625);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#660000").s().p("AinC1QgWgBgWgEIgGgBIgCgBIgMgDQgSgDgSgGQgEgCgFAAQgTABgHgIQAJgGAGgOQAFgNAFgIIADgFQAOgYAIgVIABgFIAKgYQAKgWAFgXIAAgBIADgSIAEgkIArAIIACAAIADABQAcAGAfABIAUAAIAfAAIgfAAIgUAAQgfgBgcgGIgDgBIgCAAIgrgIIAAgCIgIgHQAOgLAIgTQABgCACgCIABgBQASgLAVgGIAGgCQAIgDAGgGIAKANQAKAIAQACIAOABIAygDIAGgCIAGgCIALAAQAFACAAAHIAAACIgBAWIABAXIAAACIABADQACAFACADQAGAHADAOIAEAQIAAAAIAHAXIAAABQAGAQAAARIgBALIgBAGIgBAKIgDAOIgBAGIgCAoIAAAiIAAAPIAAgPIAAgiIACgoIABgGIADgOIABgKIABgGIABgLQAAgRgGgQIAAgBIgHgXIAAAAIgEgQQgDgOgGgHQgCgDgCgFIgBgDIAAgCIgBgXIABgWIAAgCQAAgHgFgCIApgBIAQgCIABgBQARgDASgKIAIgEQAMgFAOgDIgFgTQAKgDAFgHIABgBIAAABQgBAEACAEQAEALASACIAFAAQAaADAZgCIADgBIAAAAIABAIQADAMAEAKIABABIAHARQAHALAFAOIABADQAEANADAOQAGAVAHASQAKAYANAUQAMATAIAQIABABIACAFQAHAYgBAaQAAAFgCADIgGAIQgDAFgJACQgZAEgZAGIgFABIgJACQgzAGgxAIIgRACQgmAEgpgBQgEAAgFACIgFACQgGACgIABIgQABIhIABIhJgBgAB+CAQAaAAAZgHIACgBIACgBIAKgDQAbgKAZgHQAbgIAMgXQgMAXgbAIQgZAHgbAKIgKADIgCABIgCABQgZAHgaAAIgBAAIAAAAIgEAAIgBAAIgCAAIACAAIABAAIAEAAIAAAAIABAAgAjTB+QAKACAJAAICDAAIiDAAQgJAAgKgCQgfgGgggNQAgANAfAGgAh9BCIAJADQAOADAPAAIAaABIgagBQgPAAgOgDIgJgDIgBgBQgLgEgPAAIAAAAIAAAAIgIABIgBAAIgKAAIAAAAIgBAAIgTgBIgFgBIgCAAQgVgDgXAAIAAAAIAAAAIgJAAIAJAAIAAAAIAAAAQAXAAAVADIACAAIAFABIATABIABAAIAAAAIAKAAIABAAIAIgBIAAAAIAAAAQAPAAALAEIABABIAAAAgABWA1QAmgBAngCQACAAADgCQAVgRASgTIARgRQADgEAGgCQgGACgDAEIgRARQgSATgVARQgDACgCAAQgnACgmABIgJAAIAJAAIAAAAgAhhANQASAAAPgJIADgBIgDABQgPAJgSAAIAAAAIAAAAIgJgBQgXgDgWgHQgRgFgRgEQgSgDgXgCQAXACASADQARAEARAFQAWAHAXADIAJABIAAAAIAAAAgABKgGIAKAAIACAAQAogDAbgbQAUgVAYgOIALgFIgLAFQgYAOgUAVQgbAbgoADIgCAAIgKAAIgBAAIAAAAIgEAAIgMAAIAMAAIAEAAIAAAAIABAAgADCh8IgUAPIgVANIgKAFQgjAYgtABQAtgBAjgYIAKgFIAVgNIAUgPQADgCAEAAQgEAAgDACg");
	this.shape_5.setTransform(3.8,136.7875);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#003300").s().p("AjHGAIgCgJQgKgZgVgSIAGgEIAIgHIALgKIgLAKIgIAHIgGAEQgHAHgQgCIgYgEIgGgBIgZgDQgVgDgXgMIgGgDIgIgDQgQgMgUgIIgBgBIgFgCQgSgGgQgLQgpgagVglIgDgFIgJgVIgEgHQgKgOgJgWQgGgRAAgTIgBgPIgCgoQgCgcADgbQABgUAEgTQAEgZAJgQQATgdAagVQAYgUARgTIAEgFQAGgMAGgHQAbgcAggcQADgCADgBQAagHATgOQANgKAQgBIANAAIAAAFIAAAFIACAPIASABIABAAIAAAAQAKAAAJgBIABgBIAMgCIAOgDIABAAIAAAAIAAAAIABAAIAKgBIAAAAIAAAAQARAAAMAJIABABQADACAFABIAGACQAHACAHAAQgHAAgHgCIgGgCQgFgBgDgCIgBgBQgMgJgRAAIAAAAIAAAAIgKABIgBAAIAAAAIAAAAIgBAAIgOADIgMACIgBABQgJABgKAAIAAAAIgBAAIgSgBIgCgPIAAgFIAAgFQABgGACgDIAngWIAHAAIAAgCIABgBIACgBQAWgMAOgRQACgEADgBQAPgFAJgGQAKgFAQgDIAOgDQAhgHAlADIAOAEIAAABIgCAFQgCAMgEAJQgDAHgFAFQgDACgFAAIgKAFQgCAKgEAKIgDAGIgDAJQgFAPAAAUIAAAIQAAAUAGAMIAFAMIADAHIAMAWIAKATIAAABIAJAQIgfAQQAJgMAEgQQgEAQgJAMIABgSIABgFIgBAFIgBASIgBABIgBABQgCACAAADQAAARgNABQgRACgSAAQgFAAgCgDIgBgBIgCgCIgSgVIgNgMQgEgEgFgCQgKgCgFgIQgOgQgQgXIgGgIIBbAEIAGABQAMACAMAAQgMAAgMgCIgGgBIhbgEIAGAIQAQAXAOAQQAFAIAKACQAFACAEAEIANAMIASAVIACACIABABQACADAFAAQASAAARgCQANgBAAgRQAAgDACgCIABgBIABABQgBAWABAXQACAugMAnIgEAIQgFAHABAJQAEAXgIAMIgDAFQgCAFgCACQgGAHABAQIAEAyIABAPIABAtIABBLIAAAUIgIAHIACADQAFATgIAHIgBABQgGAGgIADIgGADQgWAFgRAMIgBAAIglgyIAPgNIAegaIgeAaIgPANIAlAyQgDACAAACQgIATgOALIgEgLgAigFGIAFAEIAFAFIgFgFIgFgEQgOgHgLgOQALAOAOAHgAiWEYIAoAVIACABIgCgBIgogVIgMgIIAMAIgAiiEQQAAAAAAgBQABAAAAAAQAAgBAAAAQAAgBAAAAIAAgEIgBgFIABgLQAFgYAAgZIAAgDQAAgagLgNIgFgHQgKgXgMgSIgUgjIgFgKIgGgUQAVgUAXgRIAIgFQARgKAGgMQgrASgjAeQgCgJAAgKIAAgCQgGAQgEAQIAMgLIAAABIADAPIAGAUIAFAKIAUAjQAMASAKAXIAFAHQALANAAAaIAAADQAAAZgFAYIgBALIABAFIAAAEQAAAAAAABQAAAAAAABQAAAAgBAAQAAABAAAAgAnwAqQAEADADAEQAZAkAnACQADABACACQgCgCgDgBQgngCgZgkQgDgEgEgDQgZgVgcgfQAcAfAZAVgAjmAyIAFgFIgFAFgAjdgLQgIAHgBAMIAJgTQAEgDADgFQAPgbATgcQgZAfgQAggAkRj5QABADADABQAaAOARAUQgRgUgagOQgDgBgBgDIgCgUIACAUgAjjlEIACAAIACAAQAYADAYAEIAFAAQAcADAbAAQgbAAgcgDIgFAAQgYgEgYgDIgCAAIgCAAIgBgBIABABgACzE4IgFAAQgSgCgFgLQgCgEABgDIABgBIAAAAQAHgaAEgaIABgPIAAgJIAAgJIAAgFIgBAAIgMgBIgBAAIAAAAIgGAAIAGAAIAAAAIABAAIAMABIABAAIAAAFIAAAJIAAAJIgBAPQgEAagHAaIAAAAIgBABQgFAGgKADIgLACIgoAEQgKABAAgIIAAgjQAPAAAIAIQACACAFABIAGACQAHACAHAAQgHAAgHgCIgGgCQgFgBgCgCQgIgIgPAAIAAgnIAAgGQAAgFACgBQALgEAMgBIAZgEQAFAAAEgCQAEgCAGgBIgCgDQgDgGgBgLQAAgKgEgKIgCgFIgEgIQgRgYgHgmIgCgKQgCgjAAgjQgChiAHhgIAOApQABAEADADIAqA0IAAgKQAAgLAEgKIAKgdQAEgKACgKQADgRAFgJIAFgHIAPgQIALgMIAIgHQAKgHACgUIABgLIgBgGIAGgDQAYgCASAOQADADAFACQAXAGARAMIAaATQAbASAWAOQAcASATAeIAQAbIALAUIAKASIAHAQQAHASACAbIACAKIABAFQABANAEAHIAJATQAFAMAEANQAPAtgEA3QgCAbADAcQAAALgGADQgCABgCAEQgJAPgNAQQgMAQgYAIIgUAGQgYAFgagBQgagBgYAFQgMACgNAAQgZAAgZACIgFABQgYAFgZAEIgCAAIAAAAIgEABIgWABIgcgCgACXEjIAIgGIgIAGgABlDuIAIADIAGACQAMACAMAAQgMAAgMgCIgGgCIgIgDQgMgIgPgEQAPAEAMAIgAEcCPIgoADQgaABgXAKIgQAIQgFACgCAFQgIALgBASQABgSAIgLQACgFAFgCIAQgIQAXgKAagBIAogDQAFgBADgDQgDADgFABgAEvCLQAugCAfgfQAPgQAOgGQADgBABgEQAGgOAKgFQgKAFgGAOQgBAEgDABQgOAGgPAQQgfAfguACIgGAAIgFAAIAIgOIACgFIADgyIARgZIAUgZIABgBIAFgGIgGAHIgGAGIgPASIgUgOQgFgVgMgNQgRgSgOgaIgNgVIgLgUQAZAxAPAtIgBAAIABAAQgPgtgZgxIALAUIANAVQAOAaARASQAMANAFAVQAFARgBAXIgDAyIgCAFIgIAOIAFAAIAGAAgAFcANIAQgRQAKgKAJgLQgTAQgOAUIgCACIAAAAgAC+gUQAfAeAvgFQgKAAgIgFQgPgJgPgHQgYgLgbgHQALAGAKAIgAF/gZIAIgHQALgJAMgDQgSACgNARIAAAAgAB6iNQgDgDgBgEIgOgpIgUgHIABgDQAGgPAEgTQACgOABgRIAAgVIgBgTQAAgFgEgDIgCgDIgHgEIgFgFQgGgLgOgOIAAAAIgBgDIgDgDQgDgHgBgHIAAgBIAAgJIANAAQAAAFgCABQgFADgGAAQAGAAAFgDQACgBAAgFIgCgDIAAAAIAAAAIACADIgNAAQACgEAFAAIABAAIAAAAIACAAIABABQgCgCgDgBIAAAAIgBAAQgCAAgDADIgBAAIAAgMQAWADARAEIAGABIAAAAIAYAEIAGABQAXAFAHAQIAEAGQATATARAMQAKAHAKAGIAAAAIAXANQAEADABAFIAAAEIAAACIAAACIABAGIgBALQgCAUgKAHIgIAHIgLAMIgPAQIgFAHQgFAJgDARQgCAKgEAKIgKAdQgEAKAAALIAAAKIgqg0gAB2jZIAQAIIALAEQAHABAHAAQgHAAgHgBIgLgEIgQgIQgNgHgKgJQAKAJANAHgACwj5IACAAIABAAIgBAAIgCAAIAAAAIgBAAQgKAAgIgFIgCgBQgFgEgFgDQgJgDgMAAIAAAAIAAAAIgPABIAPgBIAAAAIAAAAQAMAAAJADQAFADAFAEIACABQAIAFAKAAIABAAIAAAAgACmklIAEAAIAEgBIgEABIgEAAIgCAAIAAAAIgFAAQgHgCgDgEQgCgDgDAAQgFgCgDgDQgOgLgcgBQAcABAOALQADADAFACQADAAACADQADAEAHACIAFAAIAAAAIACAAgAhJiIIAAAAgAjijTIAAAAgADzkZIAAAAgAA3ljIADADIABADIgEgGgAA3ljIAAAAgAAzl7IgBgDIABAAQADgDACAAIABAAIAAAAQADABACACIgBgBIgCAAIAAAAIgBAAQgFAAgCAEIAAAAgAA+l+IAAAAg");
	this.shape_6.setTransform(0.639,89.55);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFCC66").s().p("AgYQLIhzAAIAAgFIgNgtIgEgJQgKglgHgnIgCgPIgQhfIgBgPQgBgZgKgUIgIgTIghhRIACgIIACAAIAHABQAVAFAXAAQBIACBJgCIAAAMQgDBSAJBOIADAPQAMA5AFA6IADAjQABATADARIAEATQAAADADACIgPAKIgFAAgAB9PtIAAgPQgCgCgBgDQgCgWAAgXQAAhigQhcQgGgjgJgiQgIgYgBgbIgBgMIAQgDQAygIAygGIAJgBIABAFIAFAKQAFAFAAAKQAAASADARQAEAkAAAnIACALIASBeIABAKQACA/AAA+IAAAZIh4AAgAhTFDQgIgEgNgBIgKgBIgUgDQgQgCgEAIIgLgMIACgCQAIgHgFgSIgCgDIAIgIIAAgUIAFAAIA8gsQAVgQALgNIAGgIQAJgLADgNQAIgFgBAFIACAGQALAWAdAEQADABACACIAGAKQgBAAAAAFIAAAHIgFgCIAFACIAAAmIAAAjQAAAIAKgBIAogEIALgCIAEATQgNADgNAFIgIAEQgSAKgQAEIgCAAIgPACIgpACQgDgBgFAAIgEABIgVAAQgFAAgEgCgAghhFQgDgCgCgDIgIgNQgKgOgNgXIgQgdIgLgXIgJgRIAAgBIgKgTIgMgWIgEgHIgEgLQgGgNAAgUIAAgIQAAgUAEgPIAEgJIACgGQAEgKADgKIAKgFQAFAAADgCQAEgFAEgHQAEgIACgMIACgGIAAgBIAAgBIACgKIADgdIABgJIgBAJIgCgBIgBAAIgEgBQgfgNgYgpQgzhXgGgVQgGg/AMhtQALhtAuhGQAthHBQACQBOABAyBWQAzBVAFAtQAGAsAICvQgPAegtAiQgrAhhSAnIAAAAIAAADIAAAGIAAAiIAAAMIAAADIABAKIgGAAIAAAAIgGgJIADgBIAEACIAEgCIgIAAIgDAAIgGgJIABgaIAAgFIAAAFQgFACgCACIAAAAIgIgOQADgCgBgDQgBgQgGgOQAGAOABAQQABADgDACIAIAOIAAAAQAGAGAAAJIgBAGIABABIgBAJIgGgBQgCgGAAgHQAAgHACgIIABgCIgBACQgCAIAAAHQAAAHACAGIgHAAIAAgJIAAgjIAAAjIAAAJIgFgBIgFgBIgUgFQACgHABgKIABgKQABgKAAgKQAAAKgBAKIgBAKQgBAKgCAHQgNgEgLgFQALAFANAEIgDAGIgBgBQgJgDgIAAIgBAAIAAAAIgCAAIAAAAIgCAAIACAGIgCgGIACAAIAAAAIACAAIAAAAIABAAQAIAAAJADIABABIgCADIAAAAQgDgCgGAAIAAAAIAAAAIgIABIgCAAIgEABIAEgBQADAHAKADQgQAUgOAUIgFAFQgOAIgFARQAFgRAOgIIAFgFQAOgUAQgUIABAAIAHAAIAAAAIABAAIACAAQAFAAAEgCIAEgCIABABQAIADAJABIABAOQADAZAJAQQAEAEAAAFQACAwAAAvQAAgvgCgwQAAgFgEgEQgJgQgDgZIgBgOIAAAAIAKABIABAAIAAAAIAAACQAAAUANAHIAFACQAJABAIAEIAEA0IAAALQAAAVgFATIgBACIgDAGQgIAMgDAOIgFAOIgKAeQAGgPAMgHQADgCACgFQAFgHAGgHQALgNABgSIAAgFIAEgYIABgGIAEgZIAAgIQAAgQgHgLIgDAAIgCgFIACAFQgFgBAAgGIgBgBIAEADIAFAFIAHAFIABACQAEADABAFIABATIAAAVQgBARgDAOQgDAUgGAPIgBACIAAABQgIAUgFAWIgEAOQgHAZgEAZIgDAPQgGAVgMATIgOgKgAhojqQAAAIACAHIAMApIADAIQAMASAQAcQgQgcgMgSIgDgIIgMgpQgCgHAAgIIAAgeIAAAeIAAAAgAgDmXIgIADIAIgDIAAAAgAgIjNIAFgOIAOggIABgCQAFgTAAgVIAAgLIgEg0IAIAEIABABQAAAGAFABQAFANAAASIgCATQAAAFgCAEQgIAPgIARQAIgRAIgPQACgEAAgFIACgTQAAgSgFgNIADAAQAHALAAAQIAAAIIgEAZIgBAGIgEAYIAAAFQgBASgLANQgGAHgFAHQgCAFgDACQgMAHgGAPIAKgegAgDjbIAAAAgAAIj1IADgGIgOAgQADgOAIgMgAAblYIAAAAgAAVlgQgJgKgHgMQAHAMAJAKIgIgEIAAgBIgJgDQgIgJgFgJIgFgGIgIgIIAOgCIAJAPIgJgPIAAAAIAGAAIAAAAQABAIACAHIAEAFIAAAAQAOAPAGAKIgEgDgAAVlgIAAAAgAANlkQgIgEgJgBIgFgCQgNgHAAgUIAAgCIAAAAIAIAIIAFAGQAFAJAIAJIAJADIAAABIAAAAgAgXmIIgKgBIAAAAIgBgHIAIgBIAEAIIAAABIAAAAIgBAAgAgWmIIAAAAgAgWmIIAAgBIAAABgAgWmIIAAgBIAAAAIAAgGIABgDIAHgBIAGAJIgOACIAAAAgAgWmJIAAAAgAgamRIAFgBIgBADIAAAGIAAAAIgEgIgAgymNIgBgBIAKgCIgRgBIgJgFIADgGIAUAFIAFABIAFABIAAAEIgHABIAHAAIABAHQgJgBgIgDgAhDmKIgHAAIgBAAIAGgJIABAAIABABQACACADAAIAAAAIAAAAIAEgBIAAAAIAAAAIgEABIAAAAIAAAAQgDAAgCgCIgBgBIgBAAIACgDIAJAFIAHADIgEACQgEACgFAAIgCAAIgBAAIAAAAgAgImKgAgCmKgAhLmKIAAAAgAhLmKQgKgDgDgHIACAAIAIgBIAAAAIAAAAQAGAAADACIAAAAIgGAJIAAAAgAgzmOIAAAAgAg6mRIARABIgKACIgHgDgAgpmQIAAAAgAgimRIAAAAIAAABIgHAAIAHgBgAgimRIAAAAIAIgBIAAABIgIABIAAgBgAgamRIAAgBIADAAIAAAAIABAAIABAAIAAAAIAAAAIgFABIAAAAgAg6mRIAAAAgAgimRIAAAAgAgimVIAHAAIABADIgIABIAAgEgAgVmSIAAAAIAHgCIAAABIgHABIAAAAgAgamSIgBgDIAGABIAAACIAAAAIgBAAIgBAAIAAAAIgDAAgAgVmSIAAgCIAHAAIAAAAIgHACgAgamSIAAAAgAgHmSIgEgCIgDABIAAgBIADAAIAIAAIgEACIAAAAgAhFmTIAAAAgAgOmUIAAAAIADAAIgDAAIAAAAgAgOmUIgHAAIABgJIAGAJIAAAAgAgbmVIAAAAgAgimVIAAAAgAgUmdIAAAAgAgVmeIABgGQAAgJgGgGQACgCAFgCIgBAaIgBgBg");
	this.shape_7.setTransform(6.05,92.0234);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AiPKyIgBhLIgCgtIAAgPIgEgyQgCgQAGgGQADgDABgFIADgFQAIgMgDgXQgCgJAFgHIAEgIQANgogDguQgBgXABgWIAAgCIAggQIALAXIAQAeQANAXAKANIAIAOQABACADACIAPALQAKgTAHgWIADgOQAFgZAHgZIAEgPQAFgVAIgUIAAgBIAUAHQgIBgACBjQABAjACAjIABALQAIAlAQAYIAEAIIACAFQAEAKABAKQABALADAGIACADQgGABgEACQgEACgFAAIgZAEQgNABgLAEIgGgJQgDgCgDgBQgcgEgLgWIgCgGQABgGgIAGQgDAMgJAMIgGAIQgLANgVAPIg8AtgAATG4IABAAIABAAIgBAAIgBAAIAAAAIAAAAQgJAAgDgIIAAgBIgEgIIgDgHQgBgDgCgDIgxg4IgHgJQgQgbgRgXQARAXAQAbIAHAJIAxA4QACADABADIADAHIAEAIIAAABQADAIAJAAIAAAAIAAAAgAhaEtQADANAFAKQAJAVALATIASAbIASAWQAKANADAOQgDgOgKgNIgSgWIgSgbQgLgTgJgVQgFgKgDgNIgCgGIACAGgAhdEmIABABIgBgBIgDgFIADAFgACzl6QgFgsgzhVQgyhWhOgCQhQgBgtBHQguBGgMBtQgLBtAFA/QgDgEg5ghQg4gig/guQg/gvChiwQChivB6AAQB7AACPCjQCQCiggA1QggA0hKAtQhKAtgNALQgIivgGgtg");
	this.shape_8.setTransform(4.9509,48.05);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Mathilda, new cjs.Rectangle(-55.5,-20.9,112.3,217.5), null);


(lib.Leon = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.CachedBmp_11();
	this.instance.setTransform(-61.95,-65.45,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Leon, new cjs.Rectangle(-61.9,-65.4,233,387.5), null);


(lib.flower = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// plant
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFF99").ss(0.1,1,1).p("ACjlyQgGgsASgiABxlKQgCgSgBgSQgBgRgBgRQAAgCAAgDAhHhBQABgWAKgOQACgCABgCQARgUATgKADahLQABglgQgSQgDgCgCgDACjgyQAAgZgDgZQAAgCgDgCQAAgBgBAAQgJgIgEgMACKCvQgDgpgDgoQAAgNAGgHAC3BoQgCgNABgNQABgMAFgMQACgFADgFAg9GyQAIgUAIgaQACgEABgEQABgDAAgCACUHBQAAgPACgPQAAgDAAgEQABgBAAgCQABgTALgPAC8GtQgCgHABgGQABgHAEgFADpGjQABgNgFgMAihlUQAAgbgDgcQAAgCAAgDQgBgGgDgEQgDgEgFgBAhWlUQAAgggCghQgBgFgBgFQgDgNgIgHAjTljQAAgWgFgVQAAgCgFgBQgDgBgCgDQgDgFgCgFAh+hkQADgUALgKQAGgFACgJQAAgDADgDQAFgFAFgFAjnCQQgEgeAWgVQAEgEAEgEQAFgGAOgCQACAAADgDAiICqQAAgdAQgXQAGgHAHgHQAJgKAMAAAiIGZQAlgPAbgQ");
	this.shape.setTransform(7.2781,-47.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#336633").ss(6,1,1).p("AgEnNQiUhBjeC0QBhApBNARQAdAHAaACQAsAFAjgFQBJgKAjg4QA3i6DfAFQgrCJhHBNQgYAagcATQgqAegxANACaAPQg5AMgngVQgLgGgKgHQgxAEgugJQgigHgggOQhHgfhAhBQDFhpB9BVADjgKQgUAJgRAFQgDABgCABQgQAFgPAEAA6hkQCSh2CrBxQhGA2g6AfQgKAFgKAFAA/EaQA7gPAxgoQAhgbAdgmQAug/AhhdQAEgLAEgNQgzgBgqAJAA6GWQCSh1CrBwQg7AugyAdQgCABgBAAQgVAMgTAJQgYALgVAHQhZAcg0gtQgsAEgrgHQgrgHgogTQhCgfg8g9QDFhqB9BWAgEAuQiUhAjeCzQBTAjBEARQA5APAuACQB0AGAuhKQAehnBSgs");
	this.shape_1.setTransform(5.55,-50.5465);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#663300").ss(6,1,1).p("AgUgBQAOgiAJghQACgHACgHQAOgvAHguQADgYACgYQADgmgDgmQgEg9gRg7QgQg7geg5AgiAdQAHgQAHgOAgiIYQAag4APg3QAOgvAHguQADgZACgYQADgmgDglQgEg9gRg8QgMgtgUgrQgHgNgHgO");
	this.shape_2.setTransform(8.5125,-43.075);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#33CC00").s().p("AAlHzQgsAEgrgHQgrgHgogTQhCgfg8g9QDFhqB9BWQgCAYgDAYQCSh1CrBwQg7AugyAdIgDABQgVAMgTAJQgYALgVAHQgjALgcAAQguAAgggcgAAlHzQAOgvAHguQgHAugOAvgACoG5IAAACIgBAIQgCAPAAAPQAAgPACgPIABgIIAAgCQABgUALgPQgLAPgBAUgAgZGbIgCAIIgRAvIARgvIACgIIABgFIgBAFgADNHNIgBgJIAAgFQABgHAEgFQgEAFgBAHIAAAFIABAJgAD6HDIAAgFQAAgLgEgKQAEAKAAALIAAAFgAh3G5QAlgQAbgQQgbAQglAQgAAqCiQAehnBSgsQAPgEAQgFIAEgCQASgFAUgJQgUAJgSAFIgEACQgQAFgPAEQg5AMgngVQgLgGgKgHQgxAEgugJQgigHghgOQhGgfhAhBQDFhpB9BVIgFAxQCSh2CrBxQhGA2g6AfIgUAKQAqgJAzABIgIAYQghBdguA/QgdAmghAbQgxAog7APQgEg9gRg7gACWB+IAFBQIgFhQIgBgCQAAgMAGgGQgGAGAAAMIABACgADICIIgBgPIAAgLQACgNAFgLIAEgKIgEAKQgFALgCANIAAALIABAPgAAlgHQANgvAIguQgIAugNAvgACthKIACABQADACAAADQACAZAAAZQAAgZgCgZQAAgDgDgCIgCgBQgJgIgEgLQAEALAJAIgAgnhKIgEAEQgJAPgCAWQACgWAJgPIAEgEQARgUASgJQgSAJgRAUgADrgrIAAgGQAAghgPgQIgFgFIAFAFQAPAQAAAhIAAAGgAhUh2QgCACgBADQgCAKgFAEQgLAKgEAVQAEgVALgKQAFgEACgKQABgDACgCIAKgKIgKAKgAh4DmQgugCg5gPQhEgRhTgjQDeizCUBAIAMAbQAVAsANAtQgrBFhoAAIgPgBgAhaCHQgHAHgFAIQgRAXAAAcQAAgcARgXQAFgIAHgHQAJgJAMAAQgMAAgJAJgAjWCwIgBgJQAAgZATgSIAIgIQAFgGAOgCQACAAADgCQgDACgCAAQgOACgFAGIgIAIQgTASAAAZIABAJgAgEBnIAMgeIgMAegAAqCiIAAAAgAAqlZQgjA4hJAKQgjAFgsgFQgagCgdgHQhNgRhhgpQDei0CUBBQAdA5ARA7QA3i6DfAFQgrCJhHBNQgYAagcATQgqAegxANQgEg9gRg8gAB9lwIACAhIADAlIgDglIgCghIAAgFIAAAFIAAAAgAhJmAIACALQACAgAAAhQAAghgCggIgCgLQgDgMgIgHQAIAHADAMgAiXl7QAEAEAAAHIABAFQACAbAAAcQAAgcgCgbIgBgFQAAgHgEgEQgDgDgFgBQAFABADADgAjQl2QABADADABQAFACAAABQAFAVAAAXQAAgXgFgVQAAgBgFgCQgDgBgBgDIgGgJIAGAJgAC0lSIgBgVQAAggANgaQgNAaAAAgIABAVg");
	this.shape_3.setTransform(5.55,-50.5465);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.flower, new cjs.Rectangle(-34.9,-106.2,81,119.8), null);


(lib.clouds = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.CachedBmp_10();
	this.instance.setTransform(-264.75,-32.75,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.clouds, new cjs.Rectangle(-264.7,-32.7,529.5,65.5), null);


(lib.building = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.CachedBmp_9();
	this.instance.setTransform(-592.95,-128.4,0.3566,0.3566);

	this.instance_1 = new lib.CachedBmp_8();
	this.instance_1.setTransform(-592.45,-127.9,0.3566,0.3566);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.building, new cjs.Rectangle(-592.9,-128.4,1221,312.5), null);


(lib.Apartments = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(8,1,1).p("ArNoKIClAAIAAClIilAAgAothSICMAAIAACMIiMAAgAgRisICWAAIAACWIiWAAgAqlF6ICRAAIAACRIiRAAgAJQisIB9AAIAAB9Ih9AAgAJGEMIB9AAIAAB9Ih9AAg");
	this.shape.setTransform(-174.2,272.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#330000").ss(8,1,1).p("AjgO7IAA35AjgO7IqeAAIAA7LIKeiqIAAF8IIviWIAAFoIIwi+IAAP7IowDbIAAwYAFPKsIovEP");
	this.shape_1.setTransform(-172.45,279.95);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AqkILIAAiSICRAAIAACSgAJHGIIAAh9IB9AAIAAB9gAotA6IAAiMICNAAIAACMgAgRgWIAAiWICWAAIAACWgAJRgvIAAh9IB9AAIAAB9gArNlkIAAimICmAAIAACmg");
	this.shape_2.setTransform(-174.2,272.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#33CCFF").s().p("AjgO7IAA35IAAX5IqeAAIAA7LIKeiqIAAF8IIviWIAAFoIIwi+IAAP7IowDbIAAwYIAAQYIovEPgAq2HCICRAAIAAiRIiRAAgAI1FAIB9AAIAAh9Ih9AAgAo+gOICMAAIAAiMIiMAAgAgiheICVAAIAAiWIiVAAgAI/h3IB9AAIAAh9Ih9AAgAremtIClAAIAAilIilAAg");
	this.shape_3.setTransform(-172.45,279.95);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#330000").ss(8,1,1).p("AFPKsIovEPIAA35AFPKsIAAwYIIwi+IAAP7gAjgO7IqeAAIAA7LIKeiqIAAF8IIviWIAAFo");
	this.shape_4.setTransform(-121.75,261.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f().s("#000000").ss(8,1,1).p("ArNoKIClAAIAAClIilAAgAothSICMAAIAACMIiMAAgAqlF6ICRAAIAACRIiRAAgAJRisIB9AAIAAB9Ih9AAgAJHEMIB9AAIAAB9Ih9AAgAgRisICWAAIAACWIiWAAg");
	this.shape_5.setTransform(-123.5,254.25);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AqlILIAAiSICRAAIAACSgAJGGIIAAh9IB+AAIAAB9gAotA6IAAiMICNAAIAACMgAgRgWIAAiWICVAAIAACWgAJQgvIAAh9IB9AAIAAB9gArMlkIAAimIClAAIAACmg");
	this.shape_6.setTransform(-123.5,254.25);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#33CCFF").s().p("At+O7IAA7LIKeiqIAAF8IIviWIAAFoIIwi+IAAP7IowDbIAAwYIAAQYIovEPIAA35IAAX5gAq2HCICRAAIAAiRIiRAAgAI1FAIB9AAIAAh9Ih9AAgAo+gOICMAAIAAiMIiMAAgAgiheICVAAIAAiWIiVAAgAI/h3IB9AAIAAh9Ih9AAgAremtIClAAIAAilIilAAg");
	this.shape_7.setTransform(-121.75,261.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("#330000").ss(8,1,1).p("Ai3MIIohAAIAA2FIIhiKIAAE0IHIh5IAAEkAERIsIAAtUIHIiaIAAM8InICyInIDcIAAzb");
	this.shape_8.setTransform(-73.8,236.25);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f().s("#000000").ss(8,1,1).p("ApHmoICGAAIAACGIiGAAgAHiiLIBmAAIAABlIhmAAgAgNiLIB5AAIAAB5Ih5AAgAHaDZIBmAAIAABmIhmAAgAnFhCIByAAIAABwIhyAAgAonEyIB2AAIAAB2Ih2AAg");
	this.shape_9.setTransform(-75.225,230.35);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AonGoIAAh2IB2AAIAAB2gAHaE/IAAhmIBmAAIAABmgAnFAuIAAhwIByAAIAABwgAgNgRIAAh6IB5AAIAAB6gAHiglIAAhmIBmAAIAABmgApHkhIAAiGICGAAIAACGg");
	this.shape_10.setTransform(-75.225,230.35);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#33CCFF").s().p("Ai3MIgArYMIIAA2FIIhiKIAAE1IHIh6IAAElIAANTIAAtTIHIibIAAM7InICzInIDcIAAzaIAATagAo1FtIB2AAIAAh1Ih2AAgAHMEEIBmAAIAAhmIhmAAgAnUgMIByAAIAAhxIhyAAgAgchMIB6AAIAAh6Ih6AAgAHUhgIBmAAIAAhmIhmAAgApWlcICHAAIAAiGIiHAAg");
	this.shape_11.setTransform(-73.8,236.25);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f().s("#000000").ss(8,1,1).p("AHiiLIBmAAIAABmIhmAAgAHaDaIBmAAIAABlIhmAAgApHmnICGAAIAACFIiGAAgAnFhCIByAAIAABxIhyAAgAgNiLIB5AAIAAB6Ih5AAgAonEzIB2AAIAAB1Ih2AAg");
	this.shape_12.setTransform(-32.525,199.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f().s("#330000").ss(8,1,1).p("AERkoIHIiaIAAM8InICyInIDcIAAzbIHIh6gAi3MIIohAAIAA2FIIhiKIAAE0AERIsIAAtU");
	this.shape_13.setTransform(-31.1,205.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AonGoIAAh2IB2AAIAAB2gAHaE/IAAhmIBmAAIAABmgAnFAuIAAhwIByAAIAABwgAgNgSIAAh5IB5AAIAAB5gAHiglIAAhmIBmAAIAABmgApHkhIAAiGICGAAIAACGg");
	this.shape_14.setTransform(-32.525,199.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#33CCFF").s().p("ArYMIIAA2FIIiiKIAAE1IAATagAo1FtIB2AAIAAh2Ih2AAgAnTgMIByAAIAAhxIhyAAgApWlcICGAAIAAiGIiGAAgAi2nSIHHh7IAAEmIAANTInHDcgAgbhNIB4AAIAAh5Ih4AAgAERIsgAERknIHIibIAAM8InICygAHMEEIBmAAIAAhmIhmAAgAHUhgIBmAAIAAhmIhmAAg");
	this.shape_15.setTransform(-31.1,205.4);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f().s("#330000").ss(8,1,1).p("Ai3lwIHIhgIAADnIHIh6IAAKMInICNIAAqfAi3JjIohAAIAAxZIIhhsIAADyAi3JjIAAvTAERG2InICt");
	this.shape_16.setTransform(15.55,158.8);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f().s("#000000").ss(8,1,1).p("AHihtIBmAAIAABQIhmAAgAgNhtIB5AAIAABgIh5AAgAHaCrIBmAAIAABQIhmAAgApHlNICGAAIAABpIiGAAgAonDxIB2AAIAABdIh2AAgAnFg0IByAAIAABZIhyAAg");
	this.shape_17.setTransform(14.125,154.125);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AonFOIAAhdIB2AAIAABdgAHaD7IAAhQIBmAAIAABQgAnFAlIAAhZIByAAIAABZgAgNgNIAAhgIB5AAIAABggAHigdIAAhQIBmAAIAABQgApHjkIAAhpICGAAIAABpg");
	this.shape_18.setTransform(14.125,154.125);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#33CCFF").s().p("Ai2JjIAAvTIAAPTIoiAAIAAxZIIihsIAADyIHHhgIAADnIHIh6IAAKMInICNIAAqfIAAKfInHCtgAo1EgIB2AAIAAhdIh2AAgAHMDNIBmAAIAAhQIhmAAgAnUgJIBzAAIAAhZIhzAAgAgcg8IB6AAIAAhgIh6AAgAHUhMIBmAAIAAhQIhmAAgApVkTICGAAIAAhpIiGAAg");
	this.shape_19.setTransform(15.55,158.8);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f().s("#330000").ss(8,1,1).p("Ai2JjIoiAAIAAxZIIihsIAADyIHHhgIAADnIHIh6IAAKMInICNIAAqfAERG2InHCtIAAvT");
	this.shape_20.setTransform(42.2,120.15);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f().s("#000000").ss(8,1,1).p("AgNhtIB5AAIAABgIh5AAgAnFg0IByAAIAABZIhyAAgAHihtIBmAAIAABQIhmAAgAHaCrIBmAAIAABQIhmAAgApHlNICGAAIAABpIiGAAgAonDxIB2AAIAABdIh2AAg");
	this.shape_21.setTransform(40.775,115.475);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#33CCFF").s().p("ArYJjIAAxYIIihtIAADzIHHhgIAADnIAAKdInHCuIAAvSIAAPSgAo1EfIB2AAIAAhdIh2AAgAnUgJIBzAAIAAhaIhzAAgAgcg8IB6AAIAAhgIh6AAgApVkSICGAAIAAhqIiGAAgAERG1gAERjoIHIh7IAAKMInICMgAHMDMIBmAAIAAhQIhmAAgAHUhMIBmAAIAAhQIhmAAg");
	this.shape_22.setTransform(42.2,120.15);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f().s("#000000").ss(8,1,1).p("AGHhSIBSAAIAAA8IhSAAgAGACBIBTAAIAAA9IhTAAgAlvgnIBcAAIAABDIhcAAgAnYj7IBsAAIAABPIhsAAgAgLhSIBjAAIAABIIhjAAgAm+C2IBgAAIAABGIhgAAg");
	this.shape_23.setTransform(71.75,84.7);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f().s("#330000").ss(8,1,1).p("AiUkVIFxhIIAACuIFxhcIAAHrIlxBqIAAn5AiUHNIm5AAIAAtHIG5hSIAAC3AiUHNIAAriADdFKIlxCD");
	this.shape_24.setTransform(72.9,88.225);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("Am+D8IAAhGIBgAAIAABGgAGAC+IAAg9IBTAAIAAA9gAluAcIAAhDIBbAAIAABDgAgLgKIAAhIIBiAAIAABIgAGGgWIAAg8IBTAAIAAA8gAnYisIAAhPIBsAAIAABPg");
	this.shape_25.setTransform(71.75,84.7);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#33CCFF").s().p("AiUHNIAAriIAALiIm5AAIAAtHIG5hSIAAC3IFxhIIAACuIFxhcIAAHrIlxBqIAAn5IAAH5IlxCDgAnJDZIBfAAIAAhGIhfAAgAF1CaIBSAAIAAg8IhSAAgAl6gHIBcAAIAAhDIhcAAgAgWgtIBiAAIAAhIIhiAAgAF7g5IBTAAIAAg8IhTAAgAnjjPIBsAAIAAhPIhsAAg");
	this.shape_26.setTransform(72.9,88.225);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f().s("#000000").ss(8,1,1).p("AgKhAIBiAAIAAA4IhiAAgAGABlIBTAAIAAAwIhTAAgAGHhAIBSAAIAAAvIhSAAgAnYjFIBtAAIAAA+IhtAAgAm9CPIBfAAIAAA3IhfAAgAlugfIBbAAIAAA0IhbAAg");
	this.shape_27.setTransform(102.4,60.125);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f().s("#330000").ss(8,1,1).p("ADdiKIFxhIIAAGCIlxBTgAiUjZIFxg5IAACIAiUFqIm5AAIAAqTIG5hAIAACQAiUFqIAApDADdEDIlxBn");
	this.shape_28.setTransform(103.55,62.875);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("Am9DGIAAg3IBfAAIAAA3gAGACVIAAgwIBSAAIAAAwgAlvAVIAAg0IBdAAIAAA0gAgKgIIAAg4IBiAAIAAA4gAGHgRIAAgvIBSAAIAAAvgAnYiHIAAg+IBtAAIAAA+g");
	this.shape_29.setTransform(102.4,60.125);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#33CCFF").s().p("ApNFqIAAqTIG6hAIAACQIAAJDgAnJCrIBgAAIAAg4IhgAAgAl6gFIBcAAIAAg1IhcAAgAnkiiIBtAAIAAg/IhtAAgAiTjZIFwg5IAACIIAAGNIlwBngAgWgjIBiAAIAAg5IhiAAgADdEDgADdiKIFxhIIAAGCIlxBTgAF0B5IBTAAIAAgvIhTAAgAF7gtIBSAAIAAgvIhSAAg");
	this.shape_30.setTransform(103.55,62.875);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f().s("#000000").ss(8,1,1).p("AgHhAIBIAAIAAA4IhIAAgAEkhAIA9AAIAAAvIg9AAgAlgjFIBRAAIAAA+IhRAAgAkRgfIBFAAIAAA0IhFAAgAlMCPIBHAAIAAA3IhHAAgAEfBlIA9AAIAAAwIg9AAg");
	this.shape_31.setTransform(124,41.475);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f().s("#330000").ss(8,1,1).p("ACliKIEThIIAAGCIkTBTIkTBnIlJAAIAAqTIFJhAIAACQIETg5gAhuFqIAApDAClEDIAAmN");
	this.shape_32.setTransform(124.85,44.225);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AlMDGIAAg3IBHAAIAAA3gAEeCVIAAgwIA+AAIAAAwgAkRAVIAAg0IBEAAIAAA0gAgIgIIAAg4IBJAAIAAA4gAEkgRIAAgvIA9AAIAAAvgAlgiHIAAg+IBRAAIAAA+g");
	this.shape_33.setTransform(124,41.475);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#33CCFF").s().p("Am3FqIAAqTIFJhAIAACQIAAJDgAlUCrIBHAAIAAg4IhHAAgAkagFIBFAAIAAg1IhFAAgAloiiIBRAAIAAg/IhRAAgAhujZIETg5IAACIIAAGNIkTBngAgQgjIBJAAIAAg5IhJAAgAClEDgACliKIEThIIAAGCIkTBTgAEWB5IA9AAIAAgvIg9AAgAEbgtIA+AAIAAgvIg+AAg");
	this.shape_34.setTransform(124.85,44.225);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f().s("#000000").ss(8,1,1).p("ADzgxIAzAAIAAAkIgzAAgADvBNIAzAAIAAAlIgzAAgAgGgxIA8AAIAAArIg8AAgAkliXIBDAAIAAAwIhDAAgAjjgXIA5AAIAAAnIg5AAgAkUBtIA7AAIAAArIg7AAg");
	this.shape_35.setTransform(147.175,25.65);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f().s("#330000").ss(8,1,1).p("ACKhpIDlg3IAAEnIjlA/gAhbimIDlgrIAABoAhbEVIkTAAIAAn4IETgxIAABuAhbEVIAAm7ACKDGIjlBP");
	this.shape_36.setTransform(147.875,27.725);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AkUCXIAAgqIA7AAIAAAqgADvBxIAAgkIAzAAIAAAkgAjjAQIAAgnIA5AAIAAAngAgGgGIAAgrIA8AAIAAArgADzgNIAAgkIAzAAIAAAkgAklhnIAAgvIBDAAIAAAvg");
	this.shape_37.setTransform(147.175,25.65);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#33CCFF").s().p("AhbEVgAluEVIAAn4IETgxIAABuIDlgrIAABoIDlg3IAAEnIjlA/IAAkvIAAEvIjlBPIAAm7IAAG7gAkbCDIA7AAIAAgrIg7AAgADoBdIAzAAIAAglIgzAAgAjqgEIA5AAIAAgoIg5AAgAgNgbIA8AAIAAgrIg8AAgADsgiIAzAAIAAgkIgzAAgAksh8IBDAAIAAgvIhDAAg");
	this.shape_38.setTransform(147.875,27.725);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f().s("#330000").ss(8,1,1).p("AhLDTIjkAAIAAmAIDkglIAABUIC9giIAABQIC+gqIAADhIi+AwIi9A8IAAlRAByCXIAAjn");
	this.shape_39.setTransform(173.375,16.275);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f().s("#000000").ss(8,1,1).p("ADJglIArAAIAAAbIgrAAgADGA7IAqAAIAAAcIgqAAgAgFglIAyAAIAAAhIgyAAgAjzhzIA4AAIAAAlIg4AAgAi8gSIAvAAIAAAeIgvAAgAjlBTIAxAAIAAAhIgxAAg");
	this.shape_40.setTransform(172.825,14.675);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("AjlB0IAAghIAxAAIAAAhgADGBXIAAgcIAqAAIAAAcgAi8AMIAAgeIAvAAIAAAegAgFgEIAAghIAyAAIAAAhgADJgKIAAgbIArAAIAAAbgAjzhOIAAglIA4AAIAAAlg");
	this.shape_41.setTransform(172.825,14.675);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#33CCFF").s().p("AkvDTIAAmAIDkglIAABUIAAFRgAjqBkIAxAAIAAghIgxAAgAjCgDIAwAAIAAgfIgwAAgAj4heIA4AAIAAglIg4AAgAhLh+IC9giIAABQIAADnIi9A8gAgLgUIAyAAIAAghIgyAAgAByhQIC+gqIAADhIi+AwgADABHIArAAIAAgcIgrAAgADDgaIArAAIAAgbIgrAAgAhLh+g");
	this.shape_42.setTransform(173.375,16.275);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f().s("#000000").ss(8,1,1).p("AB0gaIAZAAIAAATIgZAAgAByApIAZAAIAAAUIgZAAgAiMhQIAgAAIAAAZIggAAgAiEA7IAcAAIAAAWIgcAAgAhsgMIAbAAIAAAUIgbAAgAgDgaIAdAAIAAAYIgdAAg");
	this.shape_43.setTransform(173.1,15.15);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f().s("#330000").ss(8,1,1).p("ABCg4IBugdIAACdIhuAiIhtAqIAAjsIBtgYgAgrCUIiEAAIAAkNICEgaIAAA7ABCBqIAAii");
	this.shape_44.setTransform(173.375,16.275);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#000000").s().p("AiEBRIAAgXIAcAAIAAAXgAByA9IAAgUIAZAAIAAAUgAhsAJIAAgVIAbAAIAAAVgAgDgDIAAgXIAdAAIAAAXgAB0gHIAAgTIAZAAIAAATgAiMg2IAAgaIAgAAIAAAag");
	this.shape_45.setTransform(173.1,15.15);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#33CCFF").s().p("AivCUIAAkNICEgaIAAA7IAADsgAiHBGIAcAAIAAgXIgcAAgAhvgCIAbAAIAAgVIgbAAgAiPhCIAgAAIAAgZIggAAgAgrhYIBtgYIAAA4IAACiIAAiiIBugdIAACdIhuAiIhtAqgABvAyIAZAAIAAgUIgZAAgAgGgOIAdAAIAAgXIgdAAgABxgSIAZAAIAAgTIgZAAg");
	this.shape_46.setTransform(173.375,16.275);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f().s("#330000").ss(8,1,1).p("AgrCUIiEAAIAAkNICEgaIAAA7IBtgYIAAA4IBugdIAACdIhuAiIAAiiABCBqIhtAqIAAjs");
	this.shape_47.setTransform(194.375,7.275);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f().s("#000000").ss(8,1,1).p("AiMhQIAgAAIAAAZIggAAgAB0gaIAZAAIAAATIgZAAgAByApIAZAAIAAAUIgZAAgAgDgaIAdAAIAAAXIgdAAgAhsgMIAbAAIAAAUIgbAAgAiEA7IAcAAIAAAWIgcAAg");
	this.shape_48.setTransform(194.1,6.15);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#000000").s().p("AiEBRIAAgXIAcAAIAAAXgAByA9IAAgUIAZAAIAAAUgAhtAJIAAgVIAcAAIAAAVgAgDgDIAAgXIAcAAIAAAXgAB0gGIAAgUIAZAAIAAAUgAiMg2IAAgaIAgAAIAAAag");
	this.shape_49.setTransform(194.1,6.15);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#33CCFF").s().p("AivCUIAAkNICEgaIAAA7IBtgYIAAA4IAACiIhtAqIAAjsIAADsgAiHBGIAcAAIAAgXIgcAAgAhvgCIAbAAIAAgVIgbAAgAgGgOIAdAAIAAgXIgdAAgAiPhCIAgAAIAAgZIggAAgABCBqgABCg4IBugdIAACdIhuAigABvAyIAZAAIAAgUIgZAAgABxgSIAZAAIAAgTIgZAAg");
	this.shape_50.setTransform(194.375,7.275);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f().s("#000000").ss(8,1,1).p("AhegnIAWAAIAAAMIgWAAgAhJgGIATAAIAAAKIgTAAgAgCgNIATAAIAAAMIgTAAgABPgNIARAAIAAAKIgRAAgABNAVIARAAIAAAKIgRAAgAhZAdIATAAIAAALIgTAAg");
	this.shape_51.setTransform(207.2,0.25);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f().s("#330000").ss(8,1,1).p("AgdgrIBKgMIAAAcIBKgPIAABOIhKARIhKAVgAgdBKIhZAAIAAiGIBZgNIAAAeAAtA1IAAhQ");
	this.shape_52.setTransform(207.375,0.8);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#000000").s().p("AhZAoIAAgLIATAAIAAALgABNAfIAAgKIARAAIAAAKgAhJAEIAAgJIATAAIAAAJgAgCgBIAAgLIATAAIAAALgABOgCIAAgKIARAAIAAAKgAhfgbIAAgMIAXAAIAAAMg");
	this.shape_53.setTransform(207.2,0.25);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#33CCFF").s().p("Ah2BKIAAiFIBZgOIAAAeIBKgMIAAAcIAABQIhKAVgAgdBKIAAh1gAhbAiIATAAIAAgLIgTAAgAhLgBIATAAIAAgKIgTAAgAgDgGIASAAIAAgMIgSAAgAhgggIAWAAIAAgNIgWAAgAAtA1gAAtgbIBKgOIAABNIhKARgABLAZIARAAIAAgKIgRAAgABNgIIARAAIAAgKIgRAAg");
	this.shape_54.setTransform(207.375,0.8);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f().s("#330000").ss(8,1,1).p("AAdgLIAxgGIAAAgIgxAIIgvAJIAAgyIAvgFgAgSAgIg7AAIAAg5IA7gGIAAANAAdAXIAAgi");
	this.shape_55.setTransform(207.375,0.85);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f().s("#000000").ss(8,1,1).p("Ag9gQIAOAAIAAAFIgOAAgAAyAJIALAAIAAAEIgLAAgAAzgFIALAAIAAAEIgLAAgAgBgFIAMAAIAAAFIgMAAgAgvgCIAMAAIAAAEIgMAAgAg6ANIANAAIAAAEIgNAAg");
	this.shape_56.setTransform(207.275,0.6);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#000000").s().p("Ag6ARIAAgEIANAAIAAAEgAAyANIAAgEIALAAIAAAEgAgvACIAAgDIAMAAIAAADgAgBAAIAAgEIAMAAIAAAEgAAzgBIAAgDIALAAIAAADgAg9gKIAAgGIAOAAIAAAGg");
	this.shape_57.setTransform(207.275,0.6);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#33CCFF").s().p("AhNAfIAAg4IA7gGIAAANIAAAxgAg7APIANAAIAAgFIgNAAgAgwAAIAMAAIAAgEIgMAAgAg+gNIAOAAIAAgFIgOAAgAgSgSIAvgFIAAAMIAAAhIAAghIAxgGIAAAhIgxAGIgvAJgAAxAKIALAAIAAgDIgLAAgAgCgCIAMAAIAAgFIgMAAgAAygDIALAAIAAgEIgLAAg");
	this.shape_58.setTransform(207.375,0.85);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f().s("#330000").ss(8,1,1).p("AALgDIARgCIAAAKIgRACgAgGgFIARgBIAAADAgGAKIAAgPAgGAKIgVAAIAAgRIAVgCIAAAEAALAHIgRAD");
	this.shape_59.setTransform(207.375,0.85);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f().s("#000000").ss(8,1,1).p("AATgBIAEAAIAAABIgEAAgAASADIAEAAIAAABIgEAAgAAAgBIAEAAIAAABIgEAAgAgWgEIAFAAIAAACIgFAAgAgUAEIAEAAIAAABIgEAAgAgRAAIAFAAIAAABIgFAAg");
	this.shape_60.setTransform(207.325,0.775);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#000000").s().p("AgUAFIAAgBIAEAAIAAABgAASAEIAAgBIAEAAIAAABgAgRABIAAgBIAFAAIAAABgAATAAIAAgBIAEAAIAAABgAAAAAIAAgBIAEAAIAAABgAgWgCIAAgCIAFAAIAAACg");
	this.shape_61.setTransform(207.325,0.775);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#33CCFF").s().p("AgbAJIAAgQIAVgBIAAADIAAAOgAgVAEIAFAAIAAgBIgFAAgAgRAAIAEAAIAAAAIgEAAgAgWgDIAFAAIAAgCIgFAAgAgGgFIARgBIAAAEIARgDIAAAJIgRADIAAgJIAAAJIgRACgAASADIAEAAIAAgBIgEAAgAASAAIAEAAIAAgBIgEAAgAAAAAIAEAAIAAgBIgEAAg");
	this.shape_62.setTransform(207.375,0.85);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4}]},4).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8}]},5).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12}]},5).to({state:[{t:this.shape_19},{t:this.shape_18,p:{x:14.125,y:154.125}},{t:this.shape_17},{t:this.shape_16}]},5).to({state:[{t:this.shape_22},{t:this.shape_18,p:{x:40.775,y:115.475}},{t:this.shape_21},{t:this.shape_20}]},5).to({state:[{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23}]},5).to({state:[{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27}]},5).to({state:[{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31}]},5).to({state:[{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35}]},5).to({state:[{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39}]},5).to({state:[{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43}]},5).to({state:[{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47}]},5).to({state:[{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51}]},5).to({state:[{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55}]},5).to({state:[{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59}]},5).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-265.9,-11.5,489.2,391);


(lib.background = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// shadow_builldings
	this.instance = new lib.CachedBmp_7();
	this.instance.setTransform(-422.35,-123.3,0.3247,0.3247);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// background
	this.linker_mc = new lib.window();
	this.linker_mc.name = "linker_mc";
	this.linker_mc.setTransform(-249.05,-67.6,0.1111,0.1158,0,0,180);

	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#4727CF","#A51616"],[0,1],-0.1,350.1,-0.1,-349.9).s().p("Eg9RA2sMAAAhtXMB6jAAAMAAABtXg");
	this.shape.setTransform(0.025,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape},{t:this.linker_mc}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.background, new cjs.Rectangle(-422.3,-350,860,700), null);


// stage content:
(lib.kerkenbush_midterm1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [74];
	// timeline functions:
	this.frame_74 = function() {
		var root = this;
		stage.enableMouseOver();
		
		this.line01_txt.addEventListener("click",changeLine01);
		
		function changeLine01(){
			console.log("will change line 1");
			root.line01_txt.text = line01;
		}
		
		var line01 = "You've given me a taste for life";
		
		this.linker_mc.addEventListener("click", link.bind(this));
		
		function link(e) {
			
		var url = "https://www.instagram.com/leon_the.professional/?hl=en";
			
		var win = window.open(url, "_blank");
			
		win.focus();
			
		}
		
		this.stop();
		
		createjs.Touch.enable(stage);
		stage.mouseMoveOutside = true;
		
		var root = this;
		var midpoint = this.stage.canvas.width / 2;
		var buildRestX = this.building.x;
		
		var bugRestX = this.bughead.x;
		var bugRestY = this.bughead.y;
		
		this.bughead.on("click", function(e) {
			createjs.Tween.get(root.bughead, {override:false}).to({x: bugRestX+10, y: bugRestY+40}, 600, createjs.Ease.quintOut).call(emerge);
		});
		
		function emerge() {
			createjs.Tween.get(root.bughead, {override:false}).to({x: bugRestX, y: bugRestY}, 2200, createjs.Ease.quintIn);
		};
		
		
		
		
		this.stage.on("stagemousemove", function(e) {
		    var newX = 0;
			if (e.stageX < midpoint) {
				newX = (midpoint - e.stageX) / 20;
			} else if (e.stageX > midpoint) {
				newX = (e.stageX - midpoint) / 20;
				newX *= -1;
			}
			createjs.Tween.get(root.building, {override:true}).to({x: buildRestX + newX}, 1000, createjs.Ease.quintOut);
			createjs.Tween.get(root.clouds, {override:true}).to({x: cloudRestX + (newX / 2)}, 1000, createjs.Ease.quintOut);
		});
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(74).call(this.frame_74).wait(1));

	// Layer_1
	this.line01_txt = new cjs.Text("You're not going to lose me.", "25px 'Copperplate'");
	this.line01_txt.name = "line01_txt";
	this.line01_txt.lineHeight = 27;
	this.line01_txt.lineWidth = 420;
	this.line01_txt.parent = this;
	this.line01_txt.setTransform(596.4,243.45);

	this.timeline.addTween(cjs.Tween.get(this.line01_txt).wait(75));

	// title
	this.instance = new lib.title();
	this.instance.setTransform(245.35,205.55);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(27).to({_off:false},0).wait(1).to({regX:85.2,regY:-5.2,x:332.7,y:185.55,alpha:0.0833},0).wait(1).to({x:334.85,y:170.8,alpha:0.1667},0).wait(1).to({x:337.05,y:156.05,alpha:0.25},0).wait(1).to({x:339.2,y:141.3,alpha:0.3333},0).wait(1).to({x:341.35,y:126.55,alpha:0.4167},0).wait(1).to({x:343.55,y:111.8,alpha:0.5},0).wait(1).to({x:345.7,y:97,alpha:0.5833},0).wait(1).to({x:347.85,y:82.25,alpha:0.6667},0).wait(1).to({x:350.05,y:67.5,alpha:0.75},0).wait(1).to({x:352.2,y:52.75,alpha:0.8333},0).wait(1).to({x:354.35,y:38,alpha:0.9167},0).wait(1).to({x:356.55,y:23.25,alpha:1},0).wait(36));

	// foreground
	this.instance_1 = new lib.Leon();
	this.instance_1.setTransform(590.85,366.65,0.6729,0.7103,0,0,0,54.6,128.3);

	this.instance_2 = new lib.plantpot();
	this.instance_2.setTransform(409.4,434.45,0.6818,0.5057);

	this.instance_3 = new lib.Apartments();
	this.instance_3.setTransform(94.2,419.15,0.9046,0.7454,0,0,0,-172.2,280.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_2},{t:this.instance_1}]}).to({state:[{t:this.instance_2},{t:this.instance_1}]},4).to({state:[{t:this.instance_2},{t:this.instance_1}]},5).to({state:[{t:this.instance_2},{t:this.instance_1}]},5).to({state:[{t:this.instance_2},{t:this.instance_1}]},5).to({state:[{t:this.instance_2},{t:this.instance_1}]},5).to({state:[{t:this.instance_2},{t:this.instance_1}]},5).to({state:[{t:this.instance_2},{t:this.instance_1}]},5).to({state:[{t:this.instance_2},{t:this.instance_1}]},5).to({state:[{t:this.instance_2},{t:this.instance_1}]},5).to({state:[{t:this.instance_2},{t:this.instance_1}]},5).to({state:[{t:this.instance_2},{t:this.instance_1}]},5).to({state:[{t:this.instance_2},{t:this.instance_1}]},5).to({state:[{t:this.instance_2},{t:this.instance_1}]},5).to({state:[{t:this.instance_2},{t:this.instance_1}]},5).to({state:[{t:this.instance_2},{t:this.instance_1},{t:this.instance_3}]},5).wait(1));

	// Plant
	this.bughead = new lib.flower();
	this.bughead.name = "bughead";
	this.bughead.setTransform(400,448.85,0.3525,0.4068);

	this.timeline.addTween(cjs.Tween.get(this.bughead).wait(1).to({regX:5.5,regY:-46.3,x:401.95,y:429.95},0).wait(1).to({y:429.9},0).wait(1).to({y:429.85},0).wait(1).to({y:429.8},0).wait(1).to({y:429.75},0).wait(1).to({y:429.7},0).wait(1).to({y:429.65},0).wait(1).to({y:429.6},0).wait(1).to({y:429.55},0).wait(1).to({y:429.5},0).wait(1).to({y:429.45},0).wait(1).to({y:429.4},0).wait(1).to({y:429.35},0).wait(1).to({y:429.3},0).wait(1).to({y:429.25},0).wait(1).to({y:429.2},0).wait(1).to({y:429.15},0).wait(1).to({y:429.1},0).wait(1).to({y:429.05},0).wait(1).to({y:429},0).wait(1).to({y:428.95},0).wait(1).to({y:428.9},0).wait(1).to({y:428.85},0).wait(1).to({y:428.8},0).wait(1).to({y:428.75},0).wait(1).to({y:428.7},0).wait(1).to({y:428.65},0).wait(1).to({y:428.6},0).wait(1).to({y:428.55},0).wait(1).to({y:428.5},0).wait(1).to({y:428.45},0).wait(1).to({y:428.4},0).wait(1).to({y:428.35},0).wait(1).to({y:428.3},0).wait(1).to({y:428.25},0).wait(1).to({y:428.2},0).wait(1).to({y:428.15},0).wait(1).to({y:428.1},0).wait(1).to({y:428.05},0).wait(1).to({y:428},0).wait(1).to({y:427.95},0).wait(1).to({y:427.9},0).wait(1).to({y:427.85},0).wait(1).to({y:427.8},0).wait(1).to({y:427.75},0).wait(1).to({y:427.7},0).wait(1).to({y:427.65},0).wait(1).to({y:427.6},0).wait(1).to({y:427.55},0).wait(1).to({y:427.5},0).wait(1).to({y:425.95},0).wait(1).to({y:424.4},0).wait(1).to({y:422.9},0).wait(1).to({y:421.35},0).wait(1).to({y:419.85},0).wait(1).to({y:418.3},0).wait(1).to({y:416.8},0).wait(1).to({y:415.25},0).wait(1).to({y:413.75},0).wait(1).to({y:412.2},0).wait(1).to({y:410.7},0).wait(1).to({y:409.15},0).wait(1).to({y:407.65},0).wait(1).to({y:406.1},0).wait(1).to({y:404.6},0).wait(1).to({y:403.05},0).wait(1).to({y:401.55},0).wait(1).to({y:400},0).wait(1).to({y:398.5},0).wait(6));

	// road
	this.instance_4 = new lib.Mathilda();
	this.instance_4.setTransform(413,396.45,1,1,0,0,0,0.6,87.8);

	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#330000").ss(8,1,1).p("EgqeAbpMApjg3RMAraA29g");
	this.shape.setTransform(497.85,376.875);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFCC00").s().p("AhZWQIAArjICzAAIAALjgAgxGoIAApWIB3AAIAAJWgAgxnGIAAngIBjAAIAAHggAgXxaIAAk1IBAAAIAAE1g");
	this.shape_1.setTransform(492.85,387.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#330000").s().p("Ag77oMAraA29MhU9AAUgAiLX6ICzAAIAArkIizAAgAhjISIB3AAIAApXIh3AAgAhjldIBjAAIAAngIhjAAgAhJvwIBBAAIAAk2IhBAAg");
	this.shape_2.setTransform(497.85,376.875);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape},{t:this.instance_4}]}).wait(75));

	// building
	this.building = new lib.building();
	this.building.name = "building";
	this.building.setTransform(554.6,254.6,1,1.4023,0,0,0,0.1,0.1);

	this.timeline.addTween(cjs.Tween.get(this.building).wait(1).to({regX:17.5,regY:27.8,x:570.55,y:293.4},0).wait(1).to({x:569.15,y:293.35},0).wait(1).to({x:567.75,y:293.3},0).wait(1).to({x:566.35,y:293.25},0).wait(1).to({x:564.95,y:293.2},0).wait(1).to({x:563.55},0).wait(1).to({x:562.1,y:293.15},0).wait(1).to({x:560.7,y:293.1},0).wait(1).to({x:559.3,y:293.05},0).wait(1).to({x:557.9,y:293},0).wait(1).to({x:556.5},0).wait(1).to({x:555.1,y:292.95},0).wait(1).to({x:553.7,y:292.9},0).wait(1).to({x:552.25,y:292.85},0).wait(1).to({x:550.85,y:292.8},0).wait(1).to({x:549.45,y:292.75},0).wait(1).to({x:548.05},0).wait(1).to({x:546.65,y:292.7},0).wait(1).to({x:545.25,y:292.65},0).wait(1).to({x:543.85,y:292.6},0).wait(1).to({x:542.4,y:292.55},0).wait(1).to({x:541},0).wait(1).to({x:539.6,y:292.5},0).wait(1).to({x:538.2,y:292.45},0).wait(1).to({x:536.8,y:292.4},0).wait(1).to({x:535.4,y:292.35},0).wait(1).to({x:534,y:292.3},0).wait(48));

	// clouds
	this.clouds = new lib.clouds();
	this.clouds.name = "clouds";
	this.clouds.setTransform(709.6,57.85);
	this.clouds.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.clouds).wait(1).to({x:709.8115,y:58.475,alpha:0.037},0).wait(1).to({x:710.0229,y:59.1,alpha:0.0741},0).wait(1).to({x:710.2344,y:59.725,alpha:0.1111},0).wait(1).to({x:710.4458,y:60.35,alpha:0.1481},0).wait(1).to({x:710.6573,y:60.975,alpha:0.1852},0).wait(1).to({x:710.8688,y:61.6,alpha:0.2222},0).wait(1).to({x:711.0802,y:62.225,alpha:0.2593},0).wait(1).to({x:711.2917,y:62.85,alpha:0.2963},0).wait(1).to({x:711.5031,y:63.475,alpha:0.3333},0).wait(1).to({x:711.7146,y:64.1,alpha:0.3704},0).wait(1).to({x:711.926,y:64.725,alpha:0.4074},0).wait(1).to({x:712.1375,y:65.35,alpha:0.4444},0).wait(1).to({x:712.349,y:65.975,alpha:0.4815},0).wait(1).to({x:712.5604,y:66.6,alpha:0.5185},0).wait(1).to({x:712.7719,y:67.225,alpha:0.5556},0).wait(1).to({x:712.9833,y:67.85,alpha:0.5926},0).wait(1).to({x:713.1948,y:68.475,alpha:0.6296},0).wait(1).to({x:713.4063,y:69.1,alpha:0.6667},0).wait(1).to({x:713.6177,y:69.725,alpha:0.7037},0).wait(1).to({x:713.8292,y:70.35,alpha:0.7407},0).wait(1).to({x:714.0406,y:70.975,alpha:0.7778},0).wait(1).to({x:714.2521,y:71.6,alpha:0.8148},0).wait(1).to({x:714.4635,y:72.225,alpha:0.8519},0).wait(1).to({x:714.675,y:72.85,alpha:0.8889},0).wait(1).to({x:714.8865,y:73.475,alpha:0.9259},0).wait(1).to({x:715.0979,y:74.1,alpha:0.963},0).wait(1).to({x:715.3094,y:74.725,alpha:1},0).wait(1).to({x:715.5208,y:75.35},0).wait(1).to({x:715.7323,y:75.975},0).wait(1).to({x:715.9438,y:76.6},0).wait(1).to({x:716.1552,y:77.225},0).wait(1).to({x:716.3667,y:77.85},0).wait(1).to({x:716.5781,y:78.475},0).wait(1).to({x:716.7896,y:79.1},0).wait(1).to({x:717.001,y:79.725},0).wait(1).to({x:717.2125,y:80.35},0).wait(1).to({x:717.424,y:80.975},0).wait(1).to({x:717.6354,y:81.6},0).wait(1).to({x:717.8469,y:82.225},0).wait(1).to({x:718.0583,y:82.85},0).wait(1).to({x:718.2698,y:83.475},0).wait(1).to({x:718.4813,y:84.1},0).wait(1).to({x:718.6927,y:84.725},0).wait(1).to({x:718.9042,y:85.35},0).wait(1).to({x:719.1156,y:85.975},0).wait(1).to({x:719.3271,y:86.6},0).wait(1).to({x:719.5385,y:87.225},0).wait(1).to({x:719.75,y:87.85},0).wait(27));

	// background
	this.linker_mc = new lib.window();
	this.linker_mc.name = "linker_mc";
	this.linker_mc.setTransform(960.15,162.65,0.1279,0.228,0,0,0,135.7,140.6);

	this.instance_5 = new lib.background();
	this.instance_5.setTransform(503.75,154.45,1.54,1.0742);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_5,p:{scaleX:1.54}},{t:this.linker_mc}]}).to({state:[{t:this.instance_5,p:{scaleX:1.54}},{t:this.linker_mc}]},1).to({state:[{t:this.instance_5,p:{scaleX:1.5401}},{t:this.linker_mc}]},73).wait(1));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(353.3,28.4,829.3,529.4);
// library properties:
lib.properties = {
	id: '35B24596B9B34951B7B72DA1B9D5B444',
	width: 1000,
	height: 500,
	fps: 24,
	color: "#FF3300",
	opacity: 1.00,
	manifest: [
		{src:"images/CachedBmp_9.png?1699031046370", id:"CachedBmp_9"},
		{src:"images/CachedBmp_8.png?1699031046370", id:"CachedBmp_8"},
		{src:"images/CachedBmp_7.png?1699031046370", id:"CachedBmp_7"},
		{src:"images/kerkenbush_midterm_1_atlas_1.png?1699031046272", id:"kerkenbush_midterm_1_atlas_1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['35B24596B9B34951B7B72DA1B9D5B444'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;